ktorio/ktor-build

- .teamcity/pom.xml
- .teamcity/test/AllProjectsTest.kt
Fixes [KTOR-1110](https://youtrack.jetbrains.com/issue/KTOR-1110)
> Add missing tests for all IDs

- .teamcity/src/subprojects/build/ProjectBuild.kt
Fixes [KTOR-1111](https://youtrack.jetbrains.com/issue/KTOR-1111)
> Implement Project Doc Samples

- .teamcity/src/VcsRoots.kt
Fixes [KTOR-1111](https://youtrack.jetbrains.com/issue/KTOR-1111)
> Ktor documentation: Failed for the root '"Ktor documentation"

- .teamcity/src/subprojects/build/ProjectBuild.kt
- .teamcity/src/subprojects/build/docsamples/ProjectDocSamples.kt
Fixes [KTOR-1111](https://youtrack.jetbrains.com/issue/KTOR-1111)
> Names for build steps are missing

- .teamcity/src/subprojects/build/core/ProjectCore.kt
Defining matrix for core, native and javascript builds
> KTOR-1114 Define Core, Native and JavaScript matrix

- .gitignore
- .teamcity/src/subprojects/build/core/ProjectCore.kt
Abstract Docker setup and fix gitignore.
> KTOR-1114 Core, Native and JavaScript Configurations

- .teamcity/pom.xml
- .teamcity/test/AllProjectsTest.kt
Fixes [KTOR-1110](https://youtrack.jetbrains.com/issue/KTOR-1110)
> Tests for IDs of build types

- .teamcity/test/AllProjectsTest.kt
Fixes [KTOR-1110](https://youtrack.jetbrains.com/issue/KTOR-1110)
> Build types IDs for project Core doesn't match expected

- .teamcity/src/subprojects/build/ProjectBuild.kt
- .teamcity/src/subprojects/build/docsamples/ProjectDocSamples.kt
- .teamcity/src/subprojects/build/samples/ProjectSamples.kt
- .teamcity/test/AllProjectsTest.kt
Fixes [KTOR-1132](https://youtrack.jetbrains.com/issue/KTOR-1132)
> Build Samples

- .teamcity/src/subprojects/build/samples/ProjectSamples.kt
Fixes [KTOR-1132](https://youtrack.jetbrains.com/issue/KTOR-1132)
> VCS roots for validate all samples configuration

- .teamcity/src/subprojects/build/samples/ProjectSamples.kt
Mark the Validate all samples as composite build, and add missing empty line.
> KTOR-1132 Build Samples

- .teamcity/src/subprojects/Extensions.kt
- .teamcity/src/subprojects/VcsRoots.kt
- .teamcity/src/subprojects/build/core/CoreBuild.kt
- .teamcity/src/subprojects/build/core/JavaScriptBuild.kt
- .teamcity/src/subprojects/build/core/NativeBuild.kt
- .teamcity/src/subprojects/build/core/ProjectCore.kt
- .teamcity/src/subprojects/build/core/StressTestBuild.kt
Add support for stress tests, as well as improve naming of certain parameters/types.
> KTOR-1114 Core Build

- .teamcity/src/subprojects/release/ProjectRelease.kt
> KTOR-1170 Release

- .teamcity/src/subprojects/build/core/CodeStyleVerifyBuild.kt
- .teamcity/src/subprojects/build/core/ProjectCore.kt
- .teamcity/test/AllProjectsTest.kt
Should be merged after https://github.com/ktorio/ktor/pull/2208  (merged)
This adds a new build configuration to run [ktlint](https://github.com/pinterest/ktlint) only without build and show reports
> KTOR-1338 Add ktlint build configuration

- .teamcity/src/subprojects/release/publishing/PublishMavenBuilds.kt
https://kotlinlang.org/docs/reference/whatsnew1420.html#updated-structure-of-multiplatform-library-publications
> Remove publishMetadataPublicationToMavenRepository from maxOs publish

- .teamcity/src/subprojects/build/ProjectBuild.kt
- .teamcity/src/subprojects/build/core/CoreBuild.kt
Fixes [KTOR-1393](https://youtrack.jetbrains.com/issue/KTOR-1393)
> Add Large build log failure condition

- .teamcity/src/subprojects/build/ProjectBuild.kt
- .teamcity/src/subprojects/build/core/CodeStyleVerifyBuild.kt
Do the following changes:
- make builds green when number of errors hasn't been increased
- publish commit status to GitHub
> KTOR-1674 Change code style verifier config

- .teamcity/src/subprojects/eap/PublishSpaceBuilds.kt
- .teamcity/src/subprojects/release/ProjectRelease.kt
- .teamcity/src/subprojects/release/publishing/ProjectPublishing.kt
- .teamcity/src/subprojects/release/publishing/PublishMavenBuilds.kt
Fix [KTOR-2399](https://youtrack.jetbrains.com/issue/KTOR-2399)
> KTOR-2399 Configure npm publishing

- .teamcity/src/subprojects/eap/PublishSpaceBuilds.kt
@e5l Sorry, I forgot the eap builds.
> Publish eap builds of linuxArm64

- .teamcity/src/subprojects/VcsRoots.kt
- .teamcity/src/subprojects/build/generator/ProjectGenerator.kt
- .teamcity/src/subprojects/build/plugin/ProjectPlugin.kt
- Adds build for creating the plugin registry for the project generator to consume
- Updated some wording because there's too many kinds of plugins and generator types at play here 😂 
Before merging, I'll need to generate the proper publishing key for space and adding it to TeamCity.
> KTOR-6562 Generate plugin registry for project generator from external repository

- .teamcity/src/subprojects/build/generator/ProjectGenerator.kt
It would appear I forgot to include the VCS trigger for this build, still getting used to TeamCity 😄
> Added triggers for registry build publish

- .teamcity/src/subprojects/release/apidocs/ProjectReleaseAPIDocs.kt
According to Oleg this should fix our docs https://jetbrains.slack.com/archives/C0288D53B/p1725966071410899?thread_ts=1725962601.206569&cid=C0288D53B
Let's give it a try 🤷
> KTOR-7418 Fix Darwin API docs by replacing build agent

- .teamcity/pom.xml
- .teamcity/settings.kts
- .teamcity/src/subprojects/cli/ProjectCLI.kt
- .teamcity/src/subprojects/plugins/ProjectGradlePlugin.kt
- .teamcity/test/AllProjectsTest.kt
> Fix tests and update test data

- .teamcity/src/subprojects/VcsRoots.kt
- .teamcity/src/subprojects/build/core/StressTestBuild.kt
Trying to fix the "Changes" tab to show there are only changes related to a PR or branch. My guess is that the main branch name is misconfigured. 
- Added `refs/heads/` prefix to branch names, let's see if it is the reason
- Changed user name style to email, as email is included in VCS names by default
> Fix VCS roots

- .teamcity/src/subprojects/benchmarks/ProjectBenchmarks.kt
- .teamcity/src/subprojects/build/ProjectBuild.kt
- .teamcity/src/subprojects/build/core/APICheckBuild.kt
- .teamcity/src/subprojects/build/core/CodeStyleVerifyBuild.kt
- .teamcity/src/subprojects/build/core/DependenciesCheckBuild.kt
- .teamcity/src/subprojects/build/core/JDKBuild.kt
- .teamcity/src/subprojects/build/core/JPMSCheckBuild.kt
- .teamcity/src/subprojects/build/core/ProjectCore.kt
- .teamcity/src/subprojects/eap/PublishSpaceBuilds.kt
- .teamcity/src/subprojects/kotlinx/html/PublishKotlinxHtml.kt
- .teamcity/src/subprojects/release/publishing/PublishMavenBuilds.kt
- .teamcity/src/subprojects/release/space/PublishSpaceBuildsRelease.kt
Task: https://youtrack.jetbrains.com/issue/KTOR-7482/Run-JVM-builds-only-on-Lunix-machines
> KTOR-7482 Run JVM builds only on Linux

- .teamcity/src/subprojects/Triggers.kt
- .teamcity/src/subprojects/eap/ProjectPublishEAPToSpace.kt
- .teamcity/src/subprojects/eap/PublishSpaceBuilds.kt
- .teamcity/src/subprojects/release/publishing/ProjectPublishing.kt
- .teamcity/src/subprojects/release/publishing/PublishMavenBuilds.kt
- .teamcity/src/subprojects/release/space/ProjectPublishReleaseToSpace.kt
- .teamcity/src/subprojects/release/space/PublishSpaceBuildsRelease.kt
Issue: [KTOR-7535](https://youtrack.jetbrains.com/issue/KTOR-7535/Build-and-publish-androidNative-targets-on-CI)
> KTOR-7535: Add publication of androidNative targets

- .teamcity/src/subprojects/eap/PublishSpaceBuilds.kt
- .teamcity/src/subprojects/kotlinx/html/PublishKotlinxHtml.kt
- .teamcity/src/subprojects/release/publishing/PublicationConstants.kt
- .teamcity/src/subprojects/release/publishing/PublishMavenBuilds.kt
- .teamcity/src/subprojects/release/space/PublishSpaceBuildsRelease.kt
To be merged after https://github.com/ktorio/ktor/pull/4392
> Remove workaround for KTOR-7556

- .teamcity/src/subprojects/build/core/ProjectCore.kt
See https://youtrack.jetbrains.com/issue/KTOR-7552
> KTOR-7552 Rerun failed builds on main branch

- .teamcity/src/subprojects/eap/PublishSpaceBuilds.kt
- .teamcity/src/subprojects/release/publishing/ProjectPublishing.kt
- .teamcity/src/subprojects/release/publishing/PublicationConstants.kt
- .teamcity/src/subprojects/release/publishing/PublishMavenBuilds.kt
- .teamcity/src/subprojects/release/space/PublishSpaceBuildsRelease.kt
[KTOR-7738](https://youtrack.jetbrains.com/issue/KTOR-7738) Simplify configuration of publishing for new targets
To be merged after https://github.com/ktorio/ktor/pull/4474
> KTOR-7738 Use aggregating publish tasks

- .teamcity/src/subprojects/Agents.kt
- .teamcity/src/subprojects/benchmarks/ProjectBenchmarks.kt
- .teamcity/src/subprojects/build/ProjectBuild.kt
- .teamcity/src/subprojects/build/core/APICheckBuild.kt
- .teamcity/src/subprojects/build/core/CodeStyleVerifyBuild.kt
- .teamcity/src/subprojects/build/core/DependenciesCheckBuild.kt
- .teamcity/src/subprojects/build/core/JDKBuild.kt
- .teamcity/src/subprojects/build/core/JPMSCheckBuild.kt
- .teamcity/src/subprojects/build/core/JavaScriptBuild.kt
- .teamcity/src/subprojects/build/core/NativeBuild.kt
- .teamcity/src/subprojects/build/core/ProjectCore.kt
- .teamcity/src/subprojects/build/core/StressTestBuild.kt
- .teamcity/src/subprojects/build/core/WasmJsBuild.kt
- .teamcity/src/subprojects/cli/ProjectCLI.kt
- .teamcity/src/subprojects/eap/ProjectPublishEAPToSpace.kt
- .teamcity/src/subprojects/eap/PublishSpaceBuilds.kt
- .teamcity/src/subprojects/eap/SetBuildNumber.kt
- .teamcity/src/subprojects/kotlinx/html/PublishKotlinxHtml.kt
- .teamcity/src/subprojects/plugins/ProjectGradlePlugin.kt
- .teamcity/src/subprojects/release/ProjectRelease.kt
- .teamcity/src/subprojects/release/apidocs/ProjectReleaseAPIDocs.kt
- .teamcity/src/subprojects/release/publishing/PublishMavenBuilds.kt
- .teamcity/src/subprojects/release/space/ProjectPublishReleaseToSpace.kt
- .teamcity/src/subprojects/release/space/PublishSpaceBuildsRelease.kt
[KTOR-7826](https://youtrack.jetbrains.com/issue/KTOR-7826) Adjust memory requirements on CI
- Changed syntax for agent selection
- Configured "CodeStyle Verify" to be run on medium agents instead of small ones. So now it finishes in 4 minutes instead of 15-20 minutes 🥲
> KTOR-7826 Refactor agents requirements

- .teamcity/src/subprojects/build/core/JDKBuild.kt
- .teamcity/src/subprojects/build/core/StressTestBuild.kt
- .teamcity/src/subprojects/plugins/ProjectGradlePlugin.kt
Changes required for https://github.com/ktorio/ktor/pull/4500
> Use test.jdk to specify JDK for tests

- .teamcity/settings.kts
- .teamcity/src/subprojects/VcsRoots.kt
- .teamcity/src/subprojects/build/samples/ProjectSamples.kt
Remove websockets-chat-sample from CI
[YouTrack ticket](https://youtrack.jetbrains.com/issue/KTOR-7945/Remove-websockets-chat-sample-from-CI)
> KTOR-7945 Remove websockets-chat-sample from CI

- .teamcity/src/subprojects/build/core/JDKBuild.kt
- .teamcity/src/subprojects/build/core/NativeBuild.kt
- .teamcity/src/subprojects/eap/PublishSpaceBuilds.kt
- .teamcity/src/subprojects/release/publishing/PublishMavenBuilds.kt
- .teamcity/src/subprojects/release/publishing/Steps.kt
- .teamcity/src/subprojects/release/space/PublishSpaceBuildsRelease.kt
Tested all affected builds:
- [Publishing](https://ktor.teamcity.com/buildConfiguration/Ktor_KtorPublish_AllEAP/310148)
- [Native macOS X64](https://ktor.teamcity.com/buildConfiguration/Ktor_KtorMatrixNativeMacOSX64/310114) (saved ~30m)
- [Native macOS Arm64](https://ktor.teamcity.com/buildConfiguration/Ktor_KtorMatrixNativeMacOSArm64/310123) (saved ~1.5m)
- [Native Linux X64](https://ktor.teamcity.com/buildConfiguration/Ktor_KtorMatrixNativeLinuxX64/310117)
- [Native Windows X64](https://ktor.teamcity.com/buildConfiguration/Ktor_KtorMatrixNativeWindowsX64/310074) (saved ~30s)
> KTOR-8042 Do not install libcurl

- .teamcity/scripts/check_modified_rust_modules.sh
- .teamcity/src/subprojects/build/core/APICheckBuild.kt
- .teamcity/src/subprojects/build/core/JDKBuild.kt
- .teamcity/src/subprojects/build/core/NativeBuild.kt
- .teamcity/src/subprojects/build/core/RustUtils.kt
Attempting to disable Rust for normal builds for the sake of performance.
> Enable rust only when module is changed

- .teamcity/src/subprojects/Triggers.kt
- .teamcity/src/subprojects/VcsRoots.kt
- .teamcity/src/subprojects/build/core/APICheckBuild.kt
- .teamcity/src/subprojects/release/ReleaseBuild.kt
Update builds to follow the new branching strategy.
Active development branch for new features.  When development work is done, we merge to `release`.
Branch for bug fixes to go into the next release.  Releases will be delivered from here.
> Introduce release branch and update relevant targets; replace apiCheck
